apiVersion: v1
kind: Service
metadata:
  name: chassis-advanced-lb
spec:
  type: LoadBalancer
  loadBalancerSourceRanges:
    - "10.0.0.0/8"  # Allow only internal traffic

  # Standard service routing
  selector:
    app: product-service
  ports:
    - name: http
      port: 80
      targetPort: 8080